[package]
name = "lambda_game_engine"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "lambda_game_engine"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.29.1"
