name: Certificate Renewal

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */2 *' # Running at 1st of the month, every two months.

jobs:

  regenerate-certificate:
    name: Renew Certificates
    runs-on: ubuntu-latest
    strategy:
      matrix:
        HOST: [curse-of-mirra-arm-loadtest-hetzner, curse-of-mirra-brazil-testing, curse-of-mirra-europe-testing, curse-of-mirra-loadtesting-client, curse-of-mirra-loadtesting-server]

    steps:

    - name: Create ssh private key file from env var
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        set -ex
        mkdir -p ~/.ssh/
        sed -E 's/(-+(BEGIN|END) OPENSSH PRIVATE KEY-+) *| +/\1\n/g' <<< "$SSH_KEY" > ~/.ssh/id_ed25519
        chmod 400 ~/.ssh/id_ed25519

    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:server

    - name: Renew certificates
      env:
        HOST: ${{ matrix.HOST }}
      run: |
          set -ex
          ssh-keyscan $HOST >> ~/.ssh/known_hosts
          ssh admin@$HOST "sudo bash -c 'systemctl stop nginx && certbot renew && systemctl start nginx'" # Stops nginx to let certbot create a webserver on port 80.
          set +ex