name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.15.4]
        otp: [26.0.2]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }} # Define the elixir version [required]
          otp-version: ${{ matrix.otp }} # Define the OTP version [required]
        env:
          ImageOS: ubuntu20
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: server/deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Check Elixir Formatting
        run: mix format --check-formatted
      - name: Check Rust Formatting
        run: cargo fmt --check --manifest-path native/lambda_game_engine/Cargo.toml
      - name: Check Rust code
        run: cargo clippy --manifest-path native/lambda_game_engine/Cargo.toml -- -D warnings
      - name: Compiles without warnings
        run: mix compile --all-warnings --warnings-as-errors
      - name: Run tests
        run: mix test
