name: Deploy to LambdaClass local machine
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/local-deploy.yml

jobs:
  build-deploy:
    name: Build and deploy to LambdaClass local machine
    runs-on: ubuntu-latest
    environment:
      name: testing
      url: http://10.150.20.186:4000/

    steps:
      - uses: actions/checkout@v4

      - name: Create ssh private key file from env var
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          HOST: ${{ secrets.SSH_HOST_LOCAL }}
        run: |
          set -ex
          mkdir -p ~/.ssh/
          sed -E 's/(-+(BEGIN|END) OPENSSH PRIVATE KEY-+) *| +/\1\n/g' <<< "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 400 ~/.ssh/id_ed25519
          ssh-keyscan $HOST >> ~/.ssh/known_hosts

      - name: Copy deploy script
        env:
          SSH_PORT: ${{ secrets.SSH_PORT_LOCAL }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME_LOCAL }}
          SSH_HOST: ${{ secrets.SSH_HOST_LOCAL }}
        run: |
          set -ex
          rsync -avz --mkpath deploy.sh --port=${SSH_PORT} ${SSH_USERNAME}@${SSH_HOST}:/root/deploy-scipt/

      - name: Execute deploy script
        env:
          SSH_HOST: ${{ secrets.SSH_HOST_LOCAL }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME_LOCAL }}
          SSH_PORT: ${{ secrets.SSH_PORT_LOCAL }}
          MIX_ENV: ${{ vars.MIX_ENV }}
          PHX_SERVER: ${{ vars.PHX_SERVER }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEWRELIC_APP_NAME: ${{ vars.NEWRELIC_APP_NAME_LOCAL }}
          NEWRELIC_KEY: ${{ secrets.NEWRELIC_KEY }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          set -ex
          ssh -p ${SSH_PORT} \
              ${SSH_USERNAME}@${SSH_HOST} \
                BRANCH_NAME=${BRANCH_NAME} \
                MIX_ENV=${MIX_ENV} \
                PHX_SERVER=${PHX_SERVER} \
                SECRET_KEY_BASE=${SECRET_KEY_BASE} \
                DATABASE_URL=${DATABASE_URL} \
                NEWRELIC_APP_NAME=${NEWRELIC_APP_NAME} \
                NEWRELIC_KEY=${NEWRELIC_KEY} \
                /root/deploy-script/deploy.sh
