name: "Start Brazil instances: testing"
on:
  schedule:
    # Runs at 12:00 UTC, Monday through Friday
    - cron: "0 12 * * 1-5"
  workflow_dispatch:

jobs:
  start-brazil-instance:
    name: "Start Brazil instances: aws-testing.dark-worlds.lambdaclass.com"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_BRAZIL_INSTANCE }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_BRAZIL_INSTANCE }}
      AWS_REGION: sa-east-1

    steps:
      - name: Start Brazil instance
        run: |
          set -ex
          # Start testing instance
          aws ec2 start-instances --instance-ids i-0a6c828181e221c1e
