name: "Stop Brazil instances: testing"
on:
  schedule:
    # Runs at 23:00 UTC, Monday through Friday
    - cron: "0 23 * * 1-5"
  workflow_dispatch:

jobs:
  stop-brazil-instance:
    name: "Stop Brazil instances: aws-testing.dark-worlds.lambdaclass.com"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_BRAZIL_INSTANCE }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_BRAZIL_INSTANCE }}
      AWS_REGION: sa-east-1

    steps:
      - name: Stop Brazil instance
        run: |
          set -ex
          # Stop testing instance
          aws ec2 stop-instances --instance-ids i-0a6c828181e221c1e
