name: Deploy to Brazil testing
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/testing-brazil-deploy.yml

jobs:
  build-deploy:
    name: Build and deploy to Brazil testing
    runs-on: ubuntu-latest
    environment:
      name: testing
      url: https://brazil-testing.curseofmyrra.com/board

    steps:
      - name: Checkout deploy script
        uses: Bhacaz/checkout-files@v2
        with:
          files: deploy.sh

      - name: Create ssh private key file from env var
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          HOST: ${{ vars.BRAZIL_HOST }}
        run: |
          set -ex
          mkdir -p ~/.ssh/
          sed -E 's/(-+(BEGIN|END) OPENSSH PRIVATE KEY-+) *| +/\1\n/g' <<< "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 400 ~/.ssh/id_ed25519
          ssh-keyscan $HOST >> ~/.ssh/known_hosts

      - name: Copy deploy script
        env:
          SSH_HOST: ${{ vars.BRAZIL_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SCRIPT_SRC: "deploy.sh"
          SCRIPT_DEST: "~/deploy-script/"
        run: |
          set -ex
          rsync -avz --mkpath ${SCRIPT_SRC} ${SSH_USERNAME}@${SSH_HOST}:${SCRIPT_DEST}

      - name: Execute deploy script
        env:
          SSH_HOST: ${{ vars.BRAZIL_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          MIX_ENV: ${{ vars.MIX_ENV }}
          PHX_SERVER: ${{ vars.PHX_SERVER }}
          PHX_HOST: ${{ vars.BRAZIL_HOST }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEWRELIC_APP_NAME: ${{ vars.NEWRELIC_APP_NAME_BRAZIL }}
          NEWRELIC_KEY: ${{ secrets.NEWRELIC_KEY }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          set -ex
          ssh ${SSH_USERNAME}@${SSH_HOST} \
                BRANCH_NAME=${BRANCH_NAME} \
                MIX_ENV=${MIX_ENV} \
                PHX_SERVER=${PHX_SERVER} \
                PHX_HOST=${PHX_HOST} \
                SECRET_KEY_BASE=${SECRET_KEY_BASE} \
                DATABASE_URL=${DATABASE_URL} \
                NEWRELIC_APP_NAME=${NEWRELIC_APP_NAME} \
                NEWRELIC_KEY=${NEWRELIC_KEY} \
                /home/${SSH_USERNAME}/deploy-script/deploy.sh
